Document: remove-metapackage
Title: Debian remove-metapackage Manual
Author: <insert document author here>
Abstract: This manual describes what remove-metapackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/remove-metapackage/remove-metapackage.sgml.gz

Format: postscript
Files: /usr/share/doc/remove-metapackage/remove-metapackage.ps.gz

Format: text
Files: /usr/share/doc/remove-metapackage/remove-metapackage.text.gz

Format: HTML
Index: /usr/share/doc/remove-metapackage/html/index.html
Files: /usr/share/doc/remove-metapackage/html/*.html
